import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // For learn docs
  learnSidebar: [{ type: 'autogenerated', dirName: '.' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: '.' }],
  apiSidebar: [{ type: 'autogenerated', dirName: '.' }],
  indexersSidebar: [{ type: 'autogenerated', dirName: '.' }],
  evmSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;