apiVersion: v1
kind: Service
metadata:
  name: laos-public-docs
  labels:
    app.kubernetes.io/app: laos-public-docs
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/app: laos-public-docs
