repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/stg/values.yaml
  production:
    values:
      - ./environments/pro/values.yaml

helmfiles:
  - path: 'charts/laos-docs/helmfile.yaml'
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      {{- if hasKey .Values "host" }}
      - host: {{ .Values.host }}
      {{- end }}